title: Hello, world! I'm Emilio De Manuel Aranda
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Emilio De Manuel Aranda # add your name
author-img: rostro.jpg # add your photo
about-author: Soy un desarrollador web que se centra en el desarrollo front-end. Siempre con ganas de seguir aprendiendo. # add description
twitter: emiliodemanuel # add your Twitter handle
facebook: # add your Facebook handle
github: demanuelemilio # add your Github handle
linkedin: emilio-de-manuel-aranda-44456727
#email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
